compilation_unit = {
    SOI
    ~ namespace_member_declaration*
    ~ EOI
}

namespace_member_declaration = {
    type_declaration
}

type_declaration = {
    class_declaration
}

class_declaration = {
    class_modifier
    ~ "partial"?
    ~ "class"
    ~ identifier
    ~ class_body
}

class_modifier = @{
    "new"
    | "public"
    | "protected"
    | "private"
    | "internal"
    | "private"
    | "abstract"
    | "sealed"
    | "static"
    | unsafe_modifier
}

unsafe_modifier = @{
    "unsafe"
}

class_body = {
    "{"
    ~ class_member_declaration*
    ~ "}"
}

class_member_declaration = {
    constant_declaration
}

constant_declaration = {
    "const"
    ~ type_name
    ~ constant_declarators
    ~ ";"
}

type_name = {
    "int"
}

constant_declarators = {
    constant_declarator ~ ("," ~ constant_declarator)*
}

constant_declarator = {
    identifier
    ~ "="
    ~ constant_expression
}

constant_expression = {
    "1"
}

identifier = {
    simple_identifier
}

simple_identifier = {
    available_identifier
}

available_identifier = {
    basic_identifier
}

basic_identifier = {
    identifier_start_character
    ~ identifier_part_character*
}

identifier_start_character = {
    ASCII_ALPHA | "_"
}

identifier_part_character  = {
    ASCII_ALPHANUMERIC | "_"
}

WHITESPACE = _{ " " | NEWLINE }
COMMENT = _{ "/*" ~ (!"*/" ~ ANY)* ~ "*/" }

DEFAULT = { "default" }
NULL =  { "null" }
